# Pull latest official node image
FROM node:16.14.0-bullseye as build

# Set working directory
WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install react-scripts -g

COPY . .

RUN npm run build

# Create image based on nginx and deploy our built React app
FROM nginx:1.17-alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
