# Pull latest official node image
FROM node:16.14.0-bullseye as build

# Set working directory
WORKDIR /app

# Add /app/node_modules/.bin to environment variables
# ENV PATH /app/node_modules/.bin:$PATH

# Copy package files and install app dependencies
# COPY package.json /app/package.json

# NEW
COPY package*.json ./

RUN npm install
RUN npm install react-scripts -g

# NEW
COPY . .

# Add React app to working directory
# ADD . /app

RUN npm run build

# Expose ports
#EXPOSE 3000
#EXPOSE 35729

# Start the React app
#CMD ["npm", "start"]


# Create image based on nginx and deploy our built React app
FROM nginx:1.17-alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
